### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by ludblom** [manjaro/manjaro-docker#14]
Sorry, I may be an idiot, but the rest of the community deserve a good documentation. When I get it working I will start it.

**Comment by boredland** [comment]
Hi there! What would you like a documentation on? How to use docker? How to use Manjaro from the cli? Both are topics that you'll surely find tons of documentation on.

**Comment by alanmmckay** [comment]
@boredland Why does this repository include both a base.Dockerfile and build.Dockerfile? Documentation explaining the scenarios in which one should be leveraged over the other could be beneficial. This naming convention and assumed mutual exclusivity doesn't seem to adhere to any standard in terms of how to use docker, as far as I'm aware.

**Comment by boredland** [comment]
The "build" file includes the basics for building packages and a user that can be used to build using pacman, as can be seen when opening that file... https://github.com/manjaro/manjaro-docker/blob/main/build.Dockerfile

**Comment by boredland** [comment]
> This naming convention and assumed mutual exclusivity doesn't seem to adhere to any standard in terms of how to use docker, as far as I'm aware.

Don't even know what you want to tell me with that. Having multiple Dockerfiles, you'll want have different names for them, no? How would you name them?

**Comment by alanmmckay** [comment]
> Don't even know what you want to tell me with that.

Just that having stronger documentation would help mitigate general confusion. For the two people who voice their confusion, there are probably 200 who do not.

> Also: this repo is - to my knowledge - mostly used behind the scenes in our build pipelines.

I believe this general confusion stems from the fact that this repo is linked via the Manjaro website through the downloads page.

Regardless, I'll play around here and see if I can contribute to documentation.

**Comment by boredland** [comment]
> I believe this general confusion stems from the fact that this repo is linked via the Manjaro website through the downloads page.

Perhaps that is wrong. @philmmanjaro is that on purpose?
