### ISSUE TITLE
Missing files from glibc

### ISSUE THREAD

**Issue by 3mb3dw0rk5** [manjaro/manjaro-docker#19]
Reinstall of `glibc` is currently skipped due to `--needed` flag.
This results in missing files.

https://github.com/manjaro/manjaro-docker/blob/8b448b03356389286543b254391e2de22e7fc376/base.Dockerfile#L49

**Comment by boredland** [comment]
I realized that already and fixed it in the wrong (build) image, will give that a do-over in an instant.
