### ISSUE TITLE
available on docker hub?

### ISSUE THREAD

**Issue by zocker-160** [manjaro/manjaro-docker#3]
Is this base image available on [docker hub](https://hub.docker.com/)?

If no; it would be very useful to have an official base image I could use for my docker images.
If yes; having a reference to and from this repo here would be good.

**Comment by ScriptAutomate** [comment]
I have the same question: Is the [manjarolinux](https://hub.docker.com/u/manjarolinux) user account on Docker Hub considered the official Manjaro account? And if so, can more information be added about the images on Docker Hub itself?

**Comment by ScriptAutomate** [comment]
> I have the same question: Is the [manjarolinux](https://hub.docker.com/u/manjarolinux) user account on Docker Hub considered the official Manjaro account? And if so, can more information be added about the images on Docker Hub itself?

This can be closed, they say here that it's the official Docker account for it:
- https://github.com/manjaro/manjaro-docker/issues/1#issuecomment-568167148

I've been using https://hub.docker.com/r/manjarolinux/base

**Comment by zocker-160** [comment]
ok alright thanks, so those are indeed official ones then
