### ISSUE TITLE
devtools not found on majaro

### ISSUE THREAD

**Issue by kesarling** [manjaro/manjaro-docker#4]
![image](https://user-images.githubusercontent.com/40181666/103123353-1378ca80-46aa-11eb-893a-d0f3aa76333a.png)

**Comment by talesam** [comment]
The same thing with me. Please make sure the package has been renamed and provide the correct name please!

**Comment by talesam** [comment]
The package you have to install is `manjato-tools`
https://wiki.manjaro.org/index.php/Manjaro-tools
