### ISSUE TITLE
"failed to initialize alpm library" when using manjarolinux/base in Dockerfile

### ISSUE THREAD

**Issue by Folaht** [manjaro/manjaro-docker#6]
Assuming this project is manjarolinux/base and assuming this could be a possible issue with this repository..
I’ve made this simple Dockerfile and I’d like to upload it to the docker hub.

_Dockerfile_
```
FROM manjarolinux/base:latest
LABEL version="0.1"
LABEL maintainer="Folaht"
LABEL release-date="2021-04-31"

# Update Manjaro Linux OS and Install dependencies
RUN yes | pacman -Syu btrfs-progs

# Install Manjaro Arm Installer
RUN yes | pacman -S manjaro-arm-installer

# Run command on Docker launch
CMD ["/usr/bin/manjaro-arm-installer"]
```

However, while the script runs fine on my computer,
I run into the following issue on docker hub…

```
Step 5/7 : RUN yes | pacman -Syu btrfs-progs
---> Running in 56d1c5886ea7
e[91merror: failed to initialize alpm library
(could not find or read directory: /var/lib/pacman/)
e[0m
Removing intermediate container 56d1c5886ea7
The command '/bin/sh -c yes | pacman -Syu btrfs-progs' returned a non-zero code: 255
```

Is this an issue with this project, my dockerfile, archlinux or docker hub?

I'm saying archlinux due to coming across during websearches for solutions:

https://gitlab.archlinux.org/archlinux/archlinux-docker/-/issues/56
https://bbs.archlinux.org/viewtopic.php?id=263379

**Comment by boredland** [comment]
afaik this should be solved right now. can you retest (and reopen if this is still a problem)
